import { test as setup, expect } from './fixtures.ts'
import { execFileSync } from "node:child_process";
import { setTimeout as sleep } from "node:timers/promises";
import path from "node:path";
import fs from "node:fs";

//const authFile = 'playwright/.auth/user.json';

setup('authenticate', async ({ page }) => {
    
    await page.goto(`https://npohle.github.io/everone/`);

    const popupPromise = page.waitForEvent("popup");
    await page.getByRole("button", { name: "Sign in with Microsoft" }).click();
    const popup = await popupPromise;
  
    await popup.getByText("Use your Microsoft account.").waitFor();
    //await popup.getByLabel("Email or phone number").fill(requireEnv("TEST_USERNAME"));
    await popup.getByLabel("Email or phone number").fill(process.env.TEST_USERNAME!);
    await popup.screenshot({ path: path.join(process.env.ARTEFACTS_DIR!, "00-01-username.png") });
    await popup.getByRole("button", { name: "Next" }).click();
  
    await popup.getByText("Enter your password").waitFor();
    await popup.getByRole("textbox", { name: "Password" }).fill(process.env.TEST_PASSWORD!);
    await popup.screenshot({ path: path.join(process.env.ARTEFACTS_DIR!, "00-02-password.png") });
    await popup.getByRole("button", { name: "Next" }).click();
  
    await popup.getByText("Enter the code generated by your authenticator app").waitFor();
    const code = await generateFreshCode(process.env.TEST_TOTP_SEED!);
    await popup.getByLabel("Code").fill(code);
    await popup.getByRole("button", { name: "Next" }).click();
  
    const staySignedIn = await popup.getByText("Stay signed in?").waitFor({timeout: 5_000}).then(() => true).catch(() => false);
    if (!staySignedIn) {
        // Microsoft sometimes tries to auto-enroll a passkey right here — creation
        // fails in an automated/headless context (no platform authenticator), which
        // lands on an interrupt page instead of going straight to "Stay signed in?".
        console.log("Passkey enrollment prompt detected, cancelling it.");
        const passkeyPrompt = await popup
        .getByText(/passkey/i)
        .first()
        .waitFor({ timeout: 5_000 })
        .then(() => true)
        .catch(() => false);
        if (passkeyPrompt) {
            await popup.getByRole("button", { name: /^(cancel|skip.*)$/i }).click();
        }        
    }
    
    await popup.getByText("Stay signed in?").waitFor({timeout: 15_000});
    await popup.screenshot({ path: path.join(process.env.ARTEFACTS_DIR!, "00-03-stay.png") });
    await popup.getByRole("button", { name: "No" }).click();

    const loaded = await page.getByText("Load more").waitFor({ timeout: 15_000 }).then(() => true).catch(() => false);
    
    if (!loaded) {
        // First-time consent is also asked inside the popup, before it closes itself.
        const askforconsent = await popup
            .getByText("needs your permission to")
            .waitFor({ timeout: 5_000 })
            .then(() => true)
            .catch(() => false);
        if (askforconsent) {
            await popup.getByRole("button", { name: "Accept" }).click();
        }
        
    } else {
        console.log('Authentication successful, and the main page is loaded.');
    }

    await page.getByText("Load more").waitFor({ timeout: 15_000 })
    .then(async () => {
        await page.screenshot({ path: path.join(process.env.ARTEFACTS_DIR!, "00-04-browser.png") });
        // Serialize cookies/localStorage (storageState) and MSAL's token cache
        // (sessionStorage — storageState() alone doesn't capture that).
        console.log("Writing auth.json to " + path.join(process.env.ARTEFACTS_DIR!, "auth.json"));
        const storageState = await page.context().storageState();
        const sessionStorage = await page.sessionStorage.items();
        fs.writeFileSync(
            path.join(process.env.ARTEFACTS_DIR!, 'auth.json'),
            JSON.stringify({ storageState, sessionStorage }),
        );
        console.log("Did write auth.json to " + path.join(process.env.ARTEFACTS_DIR!, "auth.json"));
    })
    .catch(async () => {
        await page.screenshot({ path: path.join(process.env.ARTEFACTS_DIR!, "00-05-failed.png") });
        throw new Error(`Authentication failed — see ${process.env.ARTEFACTS_DIR!}/00-05-failed.png`);
    });

    

});


export const TOTP_PERIOD_MS = 30_000;

const BASE32 = /^[A-Z2-7]+=*$/;

const normalise = (seed: string) => String(seed ?? "").replace(/\s+/g, "").toUpperCase();

export function assertValidSeed(seed: string) {
  const value = normalise(seed);
  if (!value) throw new Error("TOTP seed is empty — set TEST_TOTP_SEED");
  if (!BASE32.test(value)) {
    throw new Error("TOTP seed is not valid base32 (expected characters A-Z and 2-7)");
  }
  return value;
}

/** Milliseconds the code generated at `nowMs` stays valid. */
export function millisRemainingInWindow(nowMs = Date.now(), periodMs = TOTP_PERIOD_MS) {
  const elapsed = nowMs % periodMs;
  return elapsed === 0 ? periodMs : periodMs - elapsed;
}

/**
 * @param {string} seed base32 shared secret
 * @param {{nowSeconds?: number, bin?: string}} [options]
 */
export function generateCode(seed: string, { nowSeconds, bin = "oathtool" }: { nowSeconds?: number; bin?: string } = {}) {
  const value = assertValidSeed(seed);
  const args = ["--totp", "--base32", value];
  if (nowSeconds !== undefined) args.push("--now", `@${nowSeconds}`);
  let out;
  try {
    out = execFileSync(bin, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (err: any) {
    if (err.code === "ENOENT") {
      throw new Error(`${bin} is not installed — the e2e suite needs oathtool to mint TOTP codes`);
    }
    throw new Error(`${bin} failed to generate a TOTP code (exit ${err.status})`);
  }
  const code = out.trim();
  if (!/^\d{6,8}$/.test(code)) throw new Error("oathtool did not return a numeric TOTP code");
  return code;
}

/**
 * A code with enough life left to survive typing and a round trip to Microsoft.
 * Waits out the tail of the current window rather than submitting a code that
 * expires mid-request — a classic source of flaky 2FA tests.
 */
export async function generateFreshCode(seed: string, { minRemainingMs = 8_000, bin = "oathtool" }: { minRemainingMs?: number; bin?: string } = {}) {
  const remaining = millisRemainingInWindow();
  if (remaining < minRemainingMs) await sleep(remaining + 250);
  return generateCode(seed, { bin });
}