#!/usr/bin/env bash

is_port_free() {
    local port=$1
    ! nc -z 127.0.0.1 "$port" 2>/dev/null    
}

find_port() {
    for port in "$@"; do
        if is_port_free "$port"; then
            echo "$port"
            return 0
        fi
    done

    echo "No free port found in list: $*" >&2
    return 1
}

# start caddy file server with internal TLS enabled on a free port number picked from a fixed list 
# start a browser session with a hostname mapping (required for OAuth flow). use --headed mode if not started from a bats test suite
# authenticate with Microsoft account specified in .env file or env vars
# kill caddy file server immediately after successful authentication because SPA can run without a server afterwards

function start_and_authenticate() {

    set -a
    source .env || true
    set +a

    export RUN_ID="${1}"
    export ARTEFACTS_DIR="${2}"
    export HEADED="${3}"

    echo "start_and_authenticate: RUN_ID=$RUN_ID"
    echo "start_and_authenticate: ARTEFACTS_DIR=$ARTEFACTS_DIR"
    echo "start_and_authenticate: HEADED=$HEADED"

    mkdir -p "$ARTEFACTS_DIR"

    export CADDYPORT=$(find_port "1443" "2443" "3443" "4443" "5443" "6443" "7443" "8443" "9443")    
    printf "https://127.0.0.1:${CADDYPORT}, https://npohle.github.io:${CADDYPORT} {\n log\n tls internal\n root * $(git rev-parse --show-toplevel)/\n file_server\n}" | caddy run --adapter caddyfile --config - >"$ARTEFACTS_DIR/caddy.log" 2>&1 &
    export CADDY_PID=$!

    # Wait until Caddy is actually available
    echo "Checking if Caddy is up and running on port $CADDYPORT"
    for _ in {1..50}; do
        if curl --silent --fail --insecure "https://127.0.0.1:$CADDYPORT" >/dev/null; then
            
            echo "Caddy is up and running on port $CADDYPORT"

            # agent-browser --session "$RUN_ID" close >/dev/null 2>&1 || true
            if [[ "$HEADED" == "true" ]]; then
                agent-browser --session "$RUN_ID" --args "--host-resolver-rules=MAP npohle.github.io 127.0.0.1:$CADDYPORT" --ignore-https-errors  --headed open
            else
                agent-browser --session "$RUN_ID" --args "--host-resolver-rules=MAP npohle.github.io 127.0.0.1:$CADDYPORT" --ignore-https-errors open
            fi

            agent-browser --session "$RUN_ID" open https://npohle.github.io/everone && agent-browser --session "$RUN_ID" wait --load networkidle
            
            agent-browser --session "$RUN_ID" find role button click --name "Sign in with Microsoft"
            
            agent-browser --session "$RUN_ID" wait --text "Use your Microsoft account."
            agent-browser --session "$RUN_ID" find label "Email or phone number" fill "$TEST_USERNAME"
            agent-browser --session "$RUN_ID" screenshot "$ARTEFACTS_DIR/00-01-username.png"
            agent-browser --session "$RUN_ID" find role button click --name "Next"
            
            agent-browser --session "$RUN_ID" wait --text "Enter your password"
            agent-browser --session "$RUN_ID" find label "Password" fill "$TEST_PASSWORD"
            agent-browser --session "$RUN_ID" screenshot "$ARTEFACTS_DIR/00-02-password.png"
            agent-browser --session "$RUN_ID" find role button click --name "Next"
            
            agent-browser --session "$RUN_ID" wait --text "Enter the code generated by your authenticator app"
            agent-browser --session "$RUN_ID" find label "Code" fill "$(oathtool --totp -b ${TEST_TOTP_SEED})"
            agent-browser --session "$RUN_ID" find role button click --name "Next"
            
            agent-browser --session "$RUN_ID" wait --text "Stay signed in?"
            agent-browser --session "$RUN_ID" screenshot "$ARTEFACTS_DIR/00-03-stay.png"
            agent-browser --session "$RUN_ID" find role button click --name "No"

            agent-browser --session "$RUN_ID" wait --load networkidle
            
            agent-browser --session "$RUN_ID" wait --text "Sign out"
            agent-browser --session "$RUN_ID" screenshot "$ARTEFACTS_DIR/00-04-browser.png"

            kill "$CADDY_PID" 2>/dev/null || true
            wait "$CADDY_PID" 2>/dev/null || true

            echo "Caddy was closed on port $CADDYPORT"
            
            return 0
        fi
        sleep 0.1
    done

    echo "Caddy failed to start" >&2
    cat "caddy.log" >&2
    return 1

}

# Only execute this when the file is called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then

    export RUN_ID="$(date +%Y%m%d-%H%M%S)-$$"
    export ARTEFACTS_DIR="tests/artefacts/$RUN_ID"
    
    start_and_authenticate $RUN_ID $ARTEFACTS_DIR true || exit $?
    exit $?
fi