// Real `agent-browser snapshot -i` output captured from each stage of the
// Microsoft sign-in flow (with the account email replaced). These back the unit
// tests for the snapshot parser and the step classifier, so the login state
// machine can be exercised without a browser or network access.

export const APP_SIGNED_OUT = `- navigation "Breadcrumbs" [ref=e1]
- searchbox "Search OneDrive…" [ref=e2]
- button "Sign in" [ref=e3]
- heading "Sign in to browse your OneDrive" [level=1, ref=e4]
- button "Sign in with Microsoft" [ref=e5]`;

export const APP_SIGNED_IN = `- navigation "Breadcrumbs" [ref=e1]
- searchbox "Search OneDrive…" [ref=e2]
- button "Sign out" [ref=e3]
- button "↑ Up" [ref=e4]
- combobox [expanded=false, ref=e5]: Name (Z→A)
  - option "Name (Z→A)" [selected, ref=e11]
  - option "Name (A→Z)" [ref=e12]
- listitem "📁\\n      Pictures" [level=1, ref=e7] clickable [cursor:pointer, tabindex]
- listitem "📕\\n      Getting started with OneDrive.pdf" [level=1, ref=e9] clickable [cursor:pointer, tabindex]
- button "Load more" [ref=e6]`;

export const LOGIN_EMAIL = `- heading "Sign in" [level=1, ref=e9]
- textbox "Email or phone number" [ref=e7]
- button "Forgot your username?" [ref=e8]
- button "Next" [ref=e5]
- button "Create an account" [ref=e6]
- button "Help and feedback" [expanded=false, ref=e1]
- link "Terms of use" [ref=e2]`;

export const LOGIN_PASSWORD = `- button "Back" [ref=e5]
- heading "Enter your password" [level=1, ref=e11]
- textbox "Password" [ref=e7]
- button "Show password" [ref=e8]
- button "Forgot your password?" [ref=e9]
- button "Next" [ref=e6]
- button "Use your face, fingerprint, PIN, or security key" [ref=e10]`;

export const LOGIN_TOTP = `- heading "Enter the code generated by your authenticator app" [level=1, ref=e9]
- textbox "Code" [ref=e8]
- button "Next" [ref=e5]
- checkbox "Don't ask me again on this device" [checked=true, ref=e6]
- button "Other ways to sign in" [ref=e7]
- button "Help" [expanded=false, ref=e1]`;

export const LOGIN_STAY_SIGNED_IN = `- button "Close" [ref=e5]
- heading "Stay signed in?" [level=1, ref=e9]
- link "Learn more" [ref=e6]
- button "Yes" [ref=e7]
- button "No" [ref=e8]
- button "Help" [expanded=false, ref=e1]`;

export const LOGIN_CONSENT = `- button "unverified" [ref=e5]
- heading "Read your profile" [level=3, ref=e7]
- heading "Open OneDrive files" [level=3, ref=e8]
- heading "Maintain access to data you have given everone access to" [level=3, ref=e10]
- button "Show details" [ref=e6]
- button "Deny" [ref=e11]
- button "Accept" [ref=e12]
- link "Sign out" [ref=e1]`;

export const LOGIN_ERROR = `- heading "Microsoft account Account" [level=1, ref=e2]
- heading "We're unable to complete your request" [level=2, ref=e1]`;

export const LOGIN_ACCOUNT_PICKER = `- heading "Pick an account" [level=1, ref=e1]
- button "test.user@example.com" [ref=e2]
- button "Use another account" [ref=e3]`;

export const EMPTY = `(no interactive elements)`;
